# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool:
  name: fedora

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    
    steps:
    - task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-gokalp'
    repository: 'gokalpmeric/azureagent'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'