trigger:
  branches:
    include:
      - main  # Change this to your desired branch

pool:
  name: 'magic'

steps:
- checkout: self

- task: Kubernetes@1
  displayName: 'Build and Push Docker Image with Kaniko'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'fedoradockerdesktop'
    namespace: 'default'
    command: 'apply'
    arguments: '-f $(Build.Repository.LocalPath)/kaniko.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Container Registry'
    dockerRegistryEndpoint: 'dockerhub-gokalp'
    secrets: |
      {
        "auths":{
           "https://index.docker.io/v1/":{
              "auth":"$(base64DockerAuth)"
           }
        }
      }

- script: |
    kubectl delete pod kaniko --ignore-not-found
  displayName: 'Delete Kaniko Pod'
