trigger:
- main

pool:
  name: 'magic'


stages:
- stage: BuildAndPushImage
  jobs:
  - job: BuildAndPushImage
    steps:
    - checkout: self  # Checks out the code from your repository

    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'rancher-with-kubernetesdefault'
        namespace: 'default'
        command: 'apply'
        arguments: '-f kaniko.yaml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'

    - script: |
        # Wait for Kaniko Pod to complete
        kubectl wait --for=condition=complete --timeout=600s pod/kaniko
      displayName: 'Wait for Kaniko Pod to Complete'
