trigger:
  branches:
    include:
      - main  # Change this to your desired branch

pool:
  name: 'magic'

steps:
- checkout: self
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo '$(Build.Repository.LocalPath)'
      echo '$ls'
      echo '$pwd'
      ls
      pwd

- task: Kubernetes@1
  displayName: 'Build and Push Docker Image with Kaniko'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'fedoradockerdesktop'
    namespace: 'default'
    command: 'apply'
    arguments: '-f $(Build.Repository.LocalPath)/kaniko.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Container Registry'
    dockerRegistryEndpoint: 'dockerhub-gokalp'
    forceUpdate: false
