trigger:
  branches:
    include:
      - main  # Change this to your desired branch

pool:
  pool: 'fedora'

steps:
- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'dockerhub-gokalp'  # Use the service connection name you created earlier
    repository: 'gokalpmeric/azureagentargo'  # Replace with your Docker Hub username and image repository name
    Dockerfile: '**/Dockerfile'  # Path to your Dockerfile
