apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-devops-agent-proof
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azure-devops-agent-proof
  template:
    metadata:
      labels:
        app: azure-devops-agent-proof
    spec:
      containers:
      - name: azure-devops-agent-proof
        image: gokalpmeric/azureagent:latest
        env:
        - name: AZP_URL
          value: "https://dev.azure.com/gokalpmrc/"
        - name: AZP_TOKEN
          valueFrom:
            secretKeyRef:
              name: azure-devops-agent-secret1
              key: AZP_TOKEN
        - name: AZP_AGENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: AZP_POOL
          value: "fedora"
