apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: 
    - "--dockerfile=Dockerfile"
    - "--context=dir://$(Build.Repository.LocalPath)"
    - "--destination=gokalpmeric/azureagentargo:$(Build.BuildId)"
    volumeMounts:
    - name: docker-config
      mountPath: "/kaniko/.docker"
  restartPolicy: Never
  volumes:
  - name: docker-config
    secret:
      secretName: regcred
